# Generated by Django 4.0.5 on 2022-07-04 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active_trial', models.BooleanField(default=True, verbose_name='active trial')),
                ('trial_license', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='license.license')),
            ],
        ),
    ]
