# Generated by Django 4.0.5 on 2022-06-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active_trial', models.BooleanField(default=True, verbose_name='active trial')),
                ('trial_days', models.IntegerField(default=1, verbose_name='trial days')),
            ],
        ),
    ]
