# Generated by Django 4.0.5 on 2022-06-30 12:49

from django.db import migrations


def addDefault(apps, schema_editor):
    AppSetting = apps.get_model('appsetting', 'AppSetting')
    setting = AppSetting(is_active_trial=False,)
    setting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('appsetting', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(addDefault),
    ]
