# Generated by Django 4.0.5 on 2022-07-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsetting', '0002_auto_20220704_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='pay_description',
            field=models.TextField(default='توضیحات پرداخت'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='terms',
            field=models.TextField(default='داخت'),
        ),
    ]
