# Generated by Django 4.0.5 on 2024-01-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsetting', '0002_auto_20220704_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='percent',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=6),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='winrate',
            field=models.DecimalField(decimal_places=1, default=80, max_digits=6),
        ),
    ]
