# Generated by Django 4.0.5 on 2024-01-09 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.image')),
            ],
        ),
        migrations.CreateModel(
            name='SignalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('percent', models.DecimalField(decimal_places=1, default=2.5, max_digits=6)),
                ('winrate', models.DecimalField(decimal_places=1, default=80, max_digits=6)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.broker')),
            ],
            options={
                'ordering': ['-created_datetime'],
            },
        ),
    ]
