# Generated by Django 4.0.5 on 2022-07-05 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('excerpt', models.TextField(verbose_name='خلاصه')),
                ('content', models.TextField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='publish', max_length=100)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload.image')),
            ],
            options={
                'verbose_name': 'My News',
                'verbose_name_plural': 'My News',
                'ordering': ['-created_datetime'],
            },
        ),
    ]
