# Generated by Django 4.0.5 on 2022-06-30 05:20

from django.db import migrations
import datetime


def addDefault(apps, schema_editor):
    License = apps.get_model('license', 'License')
    license1 = License(
        title="NoLicense",
        price=0,
        description="NoLicense",
        duration=datetime.timedelta(days=0),
        unlimited=True
    )
    license1.save()
    license2 = License(
        title="Trial",
        price=0,
        description="Trial",
        duration=datetime.timedelta(days=1),
        unlimited=False
    )
    license2.save()
    license3 = License(
        title="FullAccess",
        price=0,
        description="FullAccess",
        duration=datetime.timedelta(days=0),
        unlimited=True
    )
    license3.save()


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(addDefault),
    ]
