# Generated by Django 4.0.5 on 2022-06-30 05:20

from django.db import migrations
import datetime


def addDefault(apps, schema_editor):
    License = apps.get_model('license', 'License')
    license1 = License(
        id=1,
        title="Trial",
        price=0,
        description="Trial",
        duration=datetime.timedelta(days=1),
        unlimited=False,
        is_private=True
    )
    license1.save()
    license2 = License(
        id=2,
        title="Forever",
        price=0,
        description="Forever",
        duration=datetime.timedelta(seconds=0),
        unlimited=True,
        is_private=True
    )
    license2.save()


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(addDefault),
    ]
